language: python

cache: pip

matrix:
    include:
        - python: '3.5.0'
        - python: '3.5.1'
        - python: '3.5.2'
        - python: '3.6.0'
        - python: '3.6.1'
        - python: '3.6.2'

install:
  - pip install -rrequirements-test.txt
  - pip install tox-travis
  - pip install codecov
  - pip install flake8
  - pip install isort

before_script:
  - isort --check --diff
  - flake8 --max-line-length=120 .

script:
  - tox

after_success:
  - codecov
