[tool.black]
line-length = 120
target-version = ["py37"]

[tool.isort]
line_length = 120
known_first_party = "correios"
multi_line_output = 3
force_grid_wrap = 0
use_parentheses = true
include_trailing_comma = true
atomic = true
not_skip = "__init__.py"
default_section = "THIRDPARTY"
